server:
  port: 9000

eureka:
  instance:
    hostname: producer
    nonSecurePort: ${server.port:9002}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

mongostore:
  ribbon:
    DeploymentContextBasedVipAddresses: mongostore
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ReadTimeout: 5000
#    MaxAutoRetries: 2

spring.cloud.config.discovery.enabled: true
