server:
  port: 9002

spring:
  data:
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri:mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/pageviews}

eureka:
  instance:
    hostname: mongostore
    nonSecurePort: ${server.port:9002}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

spring.cloud.config.discovery.enabled: true
