server:
  port: 9000

spring:
  data:
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri:mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/pageviews}

eureka:
  instance:
    hostname: producer
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

ribbon:
  eureka:
    enabled: true

spring.cloud.config.discovery.enabled: true
