configserver:
  image: "config-server:0.0.1-SNAPSHOT"
  hostname: configserver
  name: configserver
  links:
    - eurekaserver
  environment:
     EUREKA_HOST: eurekaserver
     EUREKA_PORT: 8761
  ports:
    - "8888:8888"
