---
server:
  port: 8888

eureka:
  instance:
    hostname: configserver
    nonSecurePort: ${server.port:8888}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
